spring:
  application:
    name: popcornnight-backend
  datasource:
    url: jdbc:mysql://localhost:3306/popcornnight?useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
